vich_uploader:
    db_driver: orm

    mappings:
        collaborator_image:
             uri_prefix: /images/collaborators
             upload_destination: '%kernel.project_dir%/public/images/collaborators'
             namer: Vich\UploaderBundle\Naming\UniqidNamer